language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t insaf730hamzin/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true insaf730hamzin/react-test npm run test

after_success:
    - docker build -t insaf730hamzin/multi-client ./client
    - docker build -t insaf730hamzin/multi-nginx ./nginx
    - docker build -t insaf730hamzin/multi-server ./server
    - docker build -t insaf730hamzin/multi-worker ./worker
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push to docker hub
    - docker push insaf730hamzin/multi-client
    - docker push insaf730hamzin/multi-nginx
    - docker push insaf730hamzin/multi-server
    - docker push insaf730hamzin/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-778342911340
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY